version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    env_file: 
      - ./backend/.env
    networks:
      - app-network
    restart: always  # Auto-restart if crashed

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always  # Auto-restart if crashed
    environment:
      - VITE_BACKEND_URL=http://backend:3000  # Allow frontend to talk to backend

networks:
  app-network:
    driver: bridge
